databases:
  - name: budget_pp
    databaseName: budget_app
    user: budget_app_user
    plan: free

services:
  - type: web
    name: rails    
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s     
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app
          property: connectionString    
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction